### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by tomayac** [MeFoDy/fugu-detector#1]
https://www.npmjs.com/package/fugu-api-data 

Just in case you weren't aware. This is what powers a lot of my stuff.

**Comment by MeFoDy** [comment]
Hi Thomas,

The package is really useful, but it looks like I can't use it. I use `rows.dev[index].id` to sync data between https://fugu-tracker.web.app/js/data.json and my script, based on your Google Spreadsheet. But I can't find something that would help me sync data between the Fugu Tracker API and [fugu-api-data](https://www.npmjs.com/package/fugu-api-data). I found `blinkFeatureID` but it differs from the Fugu Tracker API feature ID.

Maybe you can help me with that?

**Comment by tomayac** [comment]
The ChromeStatus ID is supposed to be the ID. For example, Web Serial is `6577673212002304`. I'm happy to add a ChromeStatus ID field to my data source. Just opened https://github.com/tomayac/fugu-api-data/issues/1.

**Comment by MeFoDy** [comment]
> Just opened [tomayac/fugu-api-data#1](https://github.com/tomayac/fugu-api-data/issues/1).

Thank you. I'm ready to use it right after the PR is merged :)

**Comment by tomayac** [comment]
Just released `v1.18.0` that includes the ChromeStatus ID.

**Comment by MeFoDy** [comment]
Replaced my custom copy-paste script with `fugu-api-data`. Works great.

Thank you!

**Comment by tomayac** [comment]
Nice. I've just released 1.18.1 that adds the final missing ID.

**Comment by MeFoDy** [comment]
It looks like the Ink API is not presented on https://fugu-tracker.web.app/, so my https://mefody.github.io/fugu-detector/ doesn't show it either.

**Comment by tomayac** [comment]
Yes, it's a [Microsoft-initiated API](https://blogs.windows.com/msedgedev/2021/08/18/enhancing-inking-on-the-web/). It was missing the `proj-fugu` label. Fixed now.
